### PR TITLE
feat: provide a command line option to download from cli

### PR DESCRIPTION
**Pull request by vkt1414**
addresses #33 

Supports download from selection or a manifest for now. Used 'idc' as 'binary' but can be configured to anything else.

I can not get tests to initialize but I did test on colab. I would appreciate it if anyone could work on completing the tests. If there are any examples, I can follow them.

image
image

### CODE REVIEW

**Comment by fedorov** [comment]
Per discussion today:

1. consider following the dev pattern in pyradiomics for implementing cli runner: https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/scripts/__init__.py
1. try to implement the test by adding new `test_` function(s) to the unit test class in `tests/idcindex.py`

**Comment by fedorov** [comment]
@vkt1414 I have not reviewed (and it's not ready for review, as I understand), but as a quick comment - I do not think we need separate commands for downloading from selection and from manifest. I would just do `idc download`, and manage those via command line. We could also implement a mode where we can try to guess from what is passed as a parameter whether this is a UID or manifest. I am just thinking how to simplify this interface. Let's discuss tomorrow.

**Comment by vkt1414** [comment]
> @vkt1414 I have not reviewed (and it's not ready for review, as I understand), but as a quick comment - I do not think we need separate commands for downloading from selection and from manifest. I would just do `idc download`, and manage those via command line. We could also implement a mode where we can try to guess from what is passed as a parameter whether this is a UID or manifest. I am just thinking how to simplify this interface. Let's discuss tomorrow.

This PR is now ready for review.

In my opinion, the current implementation is the most intuitive and easiest to maintain as the commands are direct mirrors of the ones in index.py. Abstracting both into one command will require a lot of thought and logic for raising exceptions for various unusual combinations as the options for manifest and selection are different. For example, a user may enter --manifest-file and --seriesInstanceUID.

image
image

**Comment by fedorov** [comment]
> consider following the dev pattern in pyradiomics for implementing cli runner: https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/scripts/__init__.py

Did you consider the above from https://github.com/ImagingDataCommons/idc-index/pull/72#issuecomment-2096836642? Did you review any recommendations for best practices where those CLI scripts should be and how they should be organized?

**Comment by fedorov** [comment]
Yes, please change it back to INFO. DEBUG has way too much stuff for a regular user.

**Pull request merged**
