### PR TITLE
Add support for distributing idc-index as wheels bundling s5cmd binary

### PR DESCRIPTION
**Pull request by jcfr**
This adds support for building wheels by transitioning from the legacy `setup.py` to `pyproject.toml`.

The changes are adapted from the output of `cookiecutter gh:scientific-python/cookie` based of scientific-python/cookie@a9609a94e. See https://learn.scientific-python.org/development/

It includes:

* Support building wheels for 64-bit systems (excluding macOS arm64 for now) and
  targeting Python >= 3.8

* Extraction of package version from source control by leveraging `setuptools-scm`[^1] .Note that generated source distribution will include the relevant version metadata.

[^1]: https://setuptools-scm.readthedocs.io/en/latest/

* Infrastructure for building sphinx-based documentation.

* Pre-commit hooks for checking style

* Dependabot configuration

* GitHub workflows for continuous integration (`ci.yml`) and continuous
  development (`cd.yml`). Each time a GitHub Release is created, it
  triggers the build, test and publishing of wheels.

Notes:
* Linting exceptions have been added to `pyproject.toml`, if relevant associated "issues" should be fixed in subsequent commits.
* Requirements to have test filename starting with `test_*` has been relaxed, and configuration updated to support running traditional `unitest` tests or `pytest` ones. See https://docs.pytest.org/en/latest/how-to/unittest.html

Additionally, it fixes the formatting of python, yaml and markdown files (by using `end-of-file-fixer`, `mixed-line-ending`, `trailing-whitespace`, `black`, `blacken-docs` and `mirrors-prettier` pre-commit hooks introduced in the second commit)

--- 

Supersedes:
* https://github.com/ImagingDataCommons/idc-index/pull/20
* https://github.com/ImagingDataCommons/idc-index/pull/30

### CODE REVIEW

**Comment by jcfr** [comment]
As this introduced a new workflow, approval is required. See https://github.com/ImagingDataCommons/idc-index/actions/runs/7737229107

cc: @fedorov

**Comment by jcfr** [comment]
@vkt1414  Could you approve the workflow ? :pray:

**Comment by fedorov** [comment]
@jcfr thank you so much for your contribution! 🙏 

I assume you are still working on this (given that the tests are failing)?

**Comment by jcfr** [comment]
> I assume you are still working on this (given that the tests are failing)?

I will sort these out :ok_hand:  Can we make sure I am added to the team so that I don't have to wait for approval for each update ?

**Comment by fedorov** [comment]
@jcfr wow, I looked over this, and that's a lot of stuff I do not know, so I am just going to trust your wisdom and merge it, and deal with consequences!

**Comment by vkt1414** [comment]
I love the matrix of python versions and three OS platforms. This repo template is going to be revolutionary!

**Pull request merged**
